markdown:         redcarpet
redcarpet:
  extensions: ["tables"]
pygments:         true
permalink:        pretty

# Social

social:
  - service: facebook
    link: http://facebook.com/wearewildjokers
  - service: twitter
    link: http://twitter.com/wearewildjokers
  - service: google-plus
    link: https://plus.google.com/100242795084056372803/posts/WFH1JM2ADbA
  - service: soundcloud
    link: http://soundcloud.com/wearewildjokers
  - service: youtube
    link: https://www.youtube.com/channel/UC0JO0743wmBtJcG7oAtJh7A
  - service: instagram
    link: http://instagram.com/wearewildjokers
  - service: email
    link: mailto:wearewildjokers@gmail.com
    icon: envelope

# Setup
title:            WILD JOKERS
tagline:          ''
description: ""

url:              http://wearewildjokers.com

javascript-dir: /public/js
stylesheet-dir: /public/css
images-dir:     /public/img
docs-dir:       /public/docs
artists-dir:    /public/img/artists
releases-dir:   /public/img/releases
events-dir:     /public/img/events

simple-form: febc16137a544346020e4aee668d6bde
disqus: wildjokers

author:
  name:           'Wild Jokers'
  url:            http://wearewildjokers.com

paginate:         3
paginate_path: blog/page:num

# Custom vars
version:          1.0.0

# Navigation

navigation:
#- text: BLOG
#  url: /blog/
- text: ARTISTS
  url: /artists/
- text: RELEASES
  url: /releases/
#- text: RADIO
#  url: /radio/
#- text: EVENTS
#  url: /events/
#- text: STORE
#  url: /store/
- text: CONTACT
  url: /contact/

