# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]
pygments:         true

# Permalinks
permalink:        pretty

# Social

social: 
  facebook:          paulmmj
  twitter:           PLJNS
  google-plus:       PaulJones93
  foursquare:        PLJNS
  github:            PLJNS
  soundcloud:        PLJNS
  youtube:           paulmmj
  instagram:         PLJNS
  linkedin:          paulmmj
  email:             paulmmj@gmail.com

# Setup
title:            PLJNS.com
tagline:          'British-American Student and Developer'
description:      "Fekyll combines the simple, static, and blog-aware power of Jekyll with the most advanced responsive front-end framework in the world, Foundation. Packaged with elegant layouts right of the box, Fekyll is perfect for quickly making your GitHub project or personal page."
url:              http://PLJNS.com

javascript-dir: /public/js
stylesheet-dir: /public/css
images-dir:     /public/img
docs-dir:       /public/docs

simple-form: febc16137a544346020e4aee668d6bde
disqus: pljns

author:
  name:           'Paul Jones'
  url:            http://PLJNS.com

paginate:         3
paginate_path: blog/page:num

# Custom vars
version:          1.0.0

# Navigation

navigation:
- text: Blog
  url: /blog/
- text: Notes
  url: /notes/
  subnavigation:
    -  text: Computer Science
       url: /notes/Computer%20Science/
       subnavigation:
       - text: Data Structures
         url: /notes/Computer%20Science/Data%20Structures/
         section: Theory
       - text: Design and Analysis of Computer Algorithms
         url: /notes/Computer%20Science/Design%20and%20Analysis%20of%20Computer%20Algorithms/
         section: Theory
       - text: Information and Data Management
         url: /notes/Computer%20Science/Information%20and%20Data%20Management/
         section: Theory
       - text: Computer Architecture
         url: /notes/Computer%20Science/Computer%20Architecture/
         section: Practice
       - text: Internet Technology
         url: /notes/Computer%20Science/Internet%20Technology/
         section: Practice
       - text: Programming Languages
         url: /notes/Computer%20Science/Programming%20Languages/
         section: Practice
       - text: Software Methodology
         url: /notes/Computer%20Science/Software%20Methodology/
         section: Practice
       - text: Systems Programming
         url: /notes/Computer%20Science/Systems%20Programming/
         section: Practice
    -  text: Philosophy
       url: /notes/Philosophy/
       subnavigation:
       - text: Advanced Topics in Metaphysics
         url: /notes/Philosophy/Advanced%20Topics%20in%20Metaphysics/
         section: Graduate
       - text: Philosophy of Psychology
         url: /notes/Philosophy/Philosophy%20of%20Psychology/
         section: Graduate
       - text: Survey in Epistemology
         url: /notes/Philosophy/Survey%20in%20Epistemology/
         section: Graduate
       - text: Aristotle
         url: /notes/Philosophy/Aristotle/
         section: Undergraduate
       - text: Epistemology
         url: /notes/Philosophy/Epistemology/
         section: Undergraduate
       - text: Leibniz
         url: /notes/Philosophy/Leibniz/
         section: Undergraduate
       - text: Social and Political Philosophy
         url: /notes/Philosophy/Social%20and%20Political%20Philosophy/
         section: Undergraduate
       - text: Theory of Knowledge
         url: /notes/Philosophy/Theory%20of%20Knowledge/
         section: Undergraduate
    -  text: Mathematics
       url: /notes/Mathematics/
       subnavigation:
       - text: Introduction to Discrete Structures I
         url: /notes/Mathematics/Introduction%20to%20Discrete%20Structures%20I/
         section: For Computer Science
       - text: Introduction to Discrete Structures II
         url: /notes/Mathematics/Introduction%20to%20Discrete%20Structures%20II/
         section: For Computer Science
       - text: Introduction to Linear Algebra
         url: /notes/Mathematics/Introduction%20to%20Linear%20Algebra/
         section: Pure
- text: Projects
  url: /projects/
- text: About
  url: /about/
  subnavigation:
    -  text: Personal
       url: /about/personal/
    -  text: Professional
       url: /about/professional/
    -  text: Academic
       url: /about/academic/
- text: Contact
  url: /contact/

